-- MySQL Script generated by MySQL Workbench
-- 08 سبت, 2017 EET 01:50:04 م
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema restaurant
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema restaurant
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `restaurant` DEFAULT CHARACTER SET utf8 ;
USE `restaurant` ;

-- -----------------------------------------------------
-- Table `restaurant`.`app_restaurant_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurant`.`app_restaurant_category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `category_name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `restaurant`.`app_admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurant`.`app_admin` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(20) NOT NULL,
  `password` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `restaurant`.`app_city`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurant`.`app_city` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `city` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `restaurant`.`app_time`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurant`.`app_time` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `time` TIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `restaurant`.`app_restaurant_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurant`.`app_restaurant_info` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `restaurant_name` VARCHAR(100) NOT NULL,
  `restaurant_city` INT NOT NULL,
  `restaurant_describtion` TEXT NOT NULL,
  `restaurant_category` INT NOT NULL,
  `restaurant_time` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_app_restaurant_info_1_idx` (`restaurant_category` ASC),
  INDEX `fk_app_restaurant_info_2_idx` (`restaurant_city` ASC),
  INDEX `fk_app_restaurant_info_3_idx` (`restaurant_time` ASC),
  CONSTRAINT `fk_app_restaurant_info_1`
    FOREIGN KEY (`restaurant_category`)
    REFERENCES `restaurant`.`app_restaurant_category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_app_restaurant_info_2`
    FOREIGN KEY (`restaurant_city`)
    REFERENCES `restaurant`.`app_city` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_app_restaurant_info_3`
    FOREIGN KEY (`restaurant_time`)
    REFERENCES `restaurant`.`app_time` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `restaurant`.`app_restaurant_discount_card`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurant`.`app_restaurant_discount_card` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `card_name` VARCHAR(45) NOT NULL,
  `card_value` FLOAT NOT NULL,
  `restaurant_dis` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_app_restaurant_discount_card_1_idx` (`restaurant_dis` ASC),
  CONSTRAINT `fk_app_restaurant_discount_card_1`
    FOREIGN KEY (`restaurant_dis`)
    REFERENCES `restaurant`.`app_restaurant_info` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
